# name: Create new pull request

# on:
#   workflow_dispatch:
#   issues:
#     types: [opened, edited]
#   issue_comment:
#     types: [created, edited]

# jobs:
#   check:
#     runs-on: ubuntu-latest
#     outputs:
#       phraseExists: ${{ steps.check-body.outputs.result }}
#       commentId: ${{ steps.check-body.outputs.commentId }}
#     steps:
#       - name: Check if issue body or any comment contains 'Hey ontobot'
#         id: check-body
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const issue = await github.rest.issues.get({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: context.issue.number
#             });

#             let bodyText = issue.data.body ? issue.data.body.toLowerCase() : '';
#             let commentId = null;

#             const comments = await github.rest.issues.listComments({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: context.issue.number
#             });

#             for (const comment of comments.data) {
#               if (comment.body.toLowerCase().includes('hey ontobot')) {
#                 bodyText += ' ' + comment.body.toLowerCase();
#                 commentId = comment.id;
#               }
#             }

#             return {
#               result: bodyText.includes('hey ontobot'),
#               commentId: commentId
#             };

#   build:
#     needs: check
#     if: needs.check.outputs.phraseExists == 'true'
#     runs-on: ${{ matrix.os }}
#     container: obolibrary/odkfull:v1.4.3
#     strategy:
#       matrix:
#         python-version: ["3.9"]
#         os: [ubuntu-latest]

#     steps:
#       - name: Checkout main branch
#         uses: actions/checkout@v3

#       - name: Return issue number
#         id: gh-script-issue
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const issue_number = context.issue.number;
#             return issue_number;

#       - name: Return repository name
#         id: gh-script-repo
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const repo = context.repo.owner + "/" + context.repo.repo;
#             return repo;

#       - name: Set branch name
#         id: vars
#         run: |
#           echo "resource=src/envo/envo-edit.owl" >> $GITHUB_ENV
#           echo "branch-name=kgcl_automation_${{ steps.gh-script-issue.outputs.result }}" >> $GITHUB_ENV
#           echo "comment-id=${{ needs.check.outputs.commentId }}" >> $GITHUB_ENV

#       - name: Get jar & enable plugin.
#         run: |
#           mkdir -p robot-plugins
#           wget https://github.com/gouttegd/kgcl-java/releases/download/kgcl-java-0.3.2/kgcl-robot-plugin-0.3.2.jar -O robot-plugins/kgcl.jar
#           echo "ROBOT_PLUGINS_DIRECTORY=$(pwd)/robot-plugins/" >> "$GITHUB_ENV"

#       - name: Install dependencies
#         run: |
#           pip install ontobot-change-agent

#       - name: Run ochange
#         id: ochange
#         run: |
#           ochange process-issue ${{ env.resource }} \
#           -r ${{ steps.gh-script-repo.outputs.result }} \
#           -n ${{ steps.gh-script-issue.outputs.result }} \
#           -g ${{ secrets.GH_TOKEN }} \
#           -c ${{ env.comment-id }}
# # ! OR using standalone JAR file.
# # !          ochange process-issue ${{ env.resource }} \
# # !          -r ${{ steps.gh-script-repo.outputs.result }} \
# # !          -n ${{ steps.gh-script-issue.outputs.result }} \
# # !          -g ${{ secrets.GH_TOKEN }} \
# # !          -p ${{ env.comment-id }} \
# # !          -j kgcl-robot.jar

#       - name: Clean-up
#         run: rm -rf robot-plugins

#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v5
#         if: ${{ env.PR_TITLE }}
#         with:
#           token: ${{ secrets.GH_TOKEN }}
#           branch-suffix: short-commit-hash
#           labels: Automated
#           author: ${{ env.ISSUE_CREATOR }} <${{ env.ISSUE_CREATOR }}@users.noreply.github.com>
#           committer: ${{ env.ISSUE_CREATOR }} <${{ env.ISSUE_CREATOR }}@users.noreply.github.com>
#           body: ${{ env.PR_BODY }}
#           title: ${{ env.PR_TITLE }}
#           base: ${{ github.head_ref }}
#           branch: ${{ env.branch-name }}
