name: "Create new pull request"

on:
  workflow_dispatch:
  issues:
    types: [ opened ]

jobs:
  register:
    name: Run new command
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3

      - name: GH-Script
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            # const prNumber = context.payload.number;
            # core.exportVariable('PULL_NUMBER', prNumber);
            const label = context.payload.label;
            core.exportVariable('LABEL', label');

      - name: Test
        run: echo "$LABEL"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

            

      # - name: Install dependencies
      #   run: poetry add onto-crawler

      # - name: Run ocrawl
      #   id: ocrawl
      #   run: ocrawl process-issue -n 4 -o test.obo
      #   # env:
      #   #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     branch-suffix: short-commit-hash
      #     labels: Automated
      #     body: ${{ steps.update.outputs.BR_BODY }}
      #     title: ${{ steps.update.outputs.BR_TITLE }}